version: '3'

services:

  app:
    build: './src/app'
    volumes:
      - './src/app/html:/usr/share/nginx/html'
    ports:
      - '8000:80'

  api:
    hostname: api
    build: './src/api'
    volumes:
      - './src/api:/app'
      - './data:/data'
    ports:
      - '8080:80'
